"""apply vector columns and indexes

Revision ID: d34f9b291c85
Revises: 
Create Date: 2025-10-08 15:07:06.269575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd34f9b291c85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure vector extension is available
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_file_chunks_chat_file_id'), 'chat_file_chunks', ['chat_file_id'], unique=False)
    op.drop_column('chat_file_embeddings', 'embedding')
    op.add_column('chat_file_embeddings', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384)))
    op.create_index(op.f('ix_chat_file_embeddings_chat_file_id'), 'chat_file_embeddings', ['chat_file_id'], unique=False)
    op.create_index(op.f('ix_chat_file_embeddings_chunk_id'), 'chat_file_embeddings', ['chunk_id'], unique=False)
    op.drop_index('idx_chat_files_file_hash', table_name='chat_files')
    op.create_index(op.f('ix_chat_files_file_hash'), 'chat_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_chat_files_session_id'), 'chat_files', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_files_uploaded_by'), 'chat_files', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_column('document_chunks', 'embedding')
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384)))
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.drop_column('document_embeddings', 'embedding')
    op.add_column('document_embeddings', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384)))
    op.create_index(op.f('ix_document_embeddings_chunk_id'), 'document_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_permissions_document_id'), 'document_permissions', ['document_id'], unique=False)
    op.drop_index('idx_documents_file_hash', table_name='documents')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_message_sources_chat_file_id'), 'message_sources', ['chat_file_id'], unique=False)
    op.create_index(op.f('ix_message_sources_chunk_id'), 'message_sources', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_message_sources_document_id'), 'message_sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_message_sources_message_id'), 'message_sources', ['message_id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_system_settings_updated_by'), 'system_settings', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_departments_user_id'), 'user_departments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_departments_user_id'), table_name='user_departments')
    op.drop_index(op.f('ix_system_settings_updated_by'), table_name='system_settings')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_message_sources_message_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_document_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_chunk_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_chat_file_id'), table_name='message_sources')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.create_index('idx_documents_file_hash', 'documents', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_document_permissions_document_id'), table_name='document_permissions')
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_chunk_id'), table_name='document_embeddings')
    op.drop_column('document_embeddings', 'embedding')
    op.add_column('document_embeddings', sa.Column('embedding', postgresql.JSON(astext_type=sa.Text())))
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'embedding')
    op.add_column('document_chunks', sa.Column('embedding', postgresql.JSON(astext_type=sa.Text())))
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_files_uploaded_by'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_session_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_file_hash'), table_name='chat_files')
    op.create_index('idx_chat_files_file_hash', 'chat_files', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_chat_file_embeddings_chunk_id'), table_name='chat_file_embeddings')
    op.drop_index(op.f('ix_chat_file_embeddings_chat_file_id'), table_name='chat_file_embeddings')
    op.drop_column('chat_file_embeddings', 'embedding')
    op.add_column('chat_file_embeddings', sa.Column('embedding', postgresql.JSON(astext_type=sa.Text())))
    op.drop_index(op.f('ix_chat_file_chunks_chat_file_id'), table_name='chat_file_chunks')
    # ### end Alembic commands ###
